using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

//í‚¢‚ğŠÇ—
//Player vs Enemy

public class BattleManager : MonoBehaviour
{
    //Player‚ğæ“¾‚·‚é
    public UnitManager player;
    //Enemy‚ğæ“¾‚·‚é
    public UnitManager enemy;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    //Player‚ªEnemy‚ÉUŒ‚
    public void OnAttackButton()
    {
        player.Attack(enemy);
        if (enemy.hp > 0 ) 
        {
            EnemyTurn();
        }
        else
        {
            BattleEnd();
        }
        
    }
    //Enemy‚ªPlayer‚ÉUŒ‚
    void EnemyTurn()
    {
        enemy.Attack(player);
        if (player.hp > 0)
        {
            BattleEnd();
        }
    }

    void BattleEnd()
    {
        Debug.Log("‘ÎíI—¹");
        string currentScene = SceneManager.GetActiveScene().name;
        SceneManager.LoadScene(currentScene);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
